name: Create themes issues

on: 
  workflow_dispatch:
    inputs:
      themes_version:
        description: 'Themes version'
        required: true
      themes_release_date:
        description: 'Themes release date'
        required: true

jobs:
  create_themes_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create a default theme issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repo: github-actions-intro
          title: Default Theme
          milestone: 3.8.0
          labels: "Enhancement, Completed"
    
