name: Create themes issues

on: 
  workflow_dispatch:
    inputs:
      themes_version:
        description: 'Themes version'
        required: true
      themes_release_date:
        description: 'Themes release date'
        required: true

jobs:
  create_themes_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create a default theme issue
        id: issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ github.token }}
          repo: github-actions-intro
          title: Default Theme
          labels: "Enhancement, Completed"
          body: Test 1
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ steps.issue.outputs.number }}
          comment: Auto-closing issue
      
    
