name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Echo a string
        run: echo "Hello Bobi"
      - name: Multiline script
        run: |
          node -v
          npm -v

